FROM node:16-alpine

WORKDIR /usr/src/app

# install and cache app dependencies
COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3010

CMD ["npm", "start"]

# WORKDIR /usr/src/app

# COPY . .

# RUN npm install

# EXPOSE 3020

# CMD [ "npm", "start" ]